title: "XM Language Lab"
description: "致力于研究语言加工、语言发展及其障碍等认知神经机制研究"


location:
  - "深圳大学沧海校区"
  - "致理楼L3 1327办公室"

contact:
  - "课题组 PI 邮箱：minxu@szu.edu.cn"

links:
   - name: "深圳大学心理学院"
     url: "https://psy.szu.edu.cn"

   - name: "深圳大学"
     url: "https://www.szu.edu.cn"

copyright: "© 2026 XM Language Lab"
