title: "XM Language Lab"
description: "简介........"


favicons:
  themeColor: "#FFFFFF"
  backgroundColor: "#FFFFFF"
  faviconColor: "#000000"



location:
  - "深圳大学致理楼....."
 

contact:
  - "....@gamail.com"
  
copyright: "© 2026 XM Language Lab"

